### 20MAI0058

### 1. Demonstrate the activation function using python code 

Widely used activation functions are as follows:
1) Sigmoid

2) Tanh(Hyperbolic tangent)

3) ReLU(Rectified Linear Unit) and its varients

4) Softmax

5) Swish

Implementaion of sigmoid

In [1]:
import numpy as np
def sigmoid(z):
 return 1 / (1 + np.exp(-z))
print("Sigmoid of 6 is:",sigmoid (6))

Sigmoid of 6 is: 0.9975273768433653


In [2]:
#non-zero centric
print("Sigmoid of positive number(6) is:",sigmoid(6))

Sigmoid of positive number(6) is: 0.9975273768433653


In [3]:
print("Sigmoid of negative number(-6) is:",sigmoid(-6))

Sigmoid of negative number(-6) is: 0.0024726231566347743


In [4]:
print("Difference between Derivative of Sigmoid (6) and (-6) is:", sigmoid(6)*(1- sigmoid(6))-sigmoid(-6)*(1- sigmoid(-6)))

Difference between Derivative of Sigmoid (6) and (-6) is: -1.1709383462843448e-16


In [5]:
#vanishing gradient
print("Difference between sigmoid of 14 and 15:",sigmoid(15)-sigmoid(14))

Difference between sigmoid of 14 and 15: 5.256258007735326e-07


Implementation of TanH

In [6]:
def tanh(z):
 return np.tanh(z)
print("tanh of 5 is:",tanh(5))

tanh of 5 is: 0.9999092042625951


In [7]:
#zero-centric 
print("tanh of positive number(15) is:",tanh(15))

tanh of positive number(15) is: 0.9999999999998128


In [8]:
print("tanh of positive number(-15) is:",tanh(-15))


tanh of positive number(-15) is: -0.9999999999998128


In [9]:
#vanishing gradient
print("Difference between tanh of 14 and 15:",np.tanh(15)-np.tanh(14))


Difference between tanh of 14 and 15: 1.1957101975212936e-12


Implementation of ReLU



In [10]:
def relu(z):
  return max(0, z)
z= 12
print("ReLU of "+str(z)+" is :",relu(z))

ReLU of 12 is : 12


In [11]:
#Dead neuron
z= -0.4
print("ReLU of "+str(z)+" is :",relu(z)) 
z= -50
print("ReLU of "+str(z)+" is :",z * (z > 0))

ReLU of -0.4 is : 0
ReLU of -50 is : 0


Implementation of Leaky ReLU



In [12]:
def leakyrelu(z):
  return np.maximum(0.01 * z, z)
z= 12
print("ReLU of "+str(z)+" is :",leakyrelu(z)) #positive value

ReLU of 12 is : 12.0


In [13]:
z= -12
print("ReLU of "+str(z)+" is :",leakyrelu(z)) #negative number

ReLU of -12 is : -0.12


Implementation of Parametric ReLU



In [14]:
def parmetricrelu(z,α):
  return np.maximum(α * z, z)
print("ReLU of "+str(z)+" is :",parmetricrelu(10,0.5)) #positive value

print("ReLU of "+str(z)+" is :",parmetricrelu(-1,0.5)) #negative number

ReLU of -12 is : 10.0
ReLU of -12 is : -0.5


In [15]:
#implementation of exponentialRelu
def erelu(z,alpha):
    return z if z >= 0 else alpha*(np.exp(z) -1)
print("Exponential ReLu for 10 is :",erelu(10,3))
print("Exponential ReLu for -10 is :",erelu(-10,3))

Exponential ReLu for 10 is : 10
Exponential ReLu for -10 is : -2.9998638002107123


Implementation of softmax

In [16]:
def softmax(x):
    ex = np.exp(x)
    sum_ex = np.sum( np.exp(x))
    return ex/sum_ex


print ("softmax of 1,2 and 3 is:",softmax([1,2,3]))

softmax of 1,2 and 3 is: [0.09003057 0.24472847 0.66524096]


2.Write a python code to filter the given image using following size of the 
filters (receptive field) 
hyper parameters (box filter) 
1. filter size (3*3) and (5*5) 
2. filter size (3*3) and (5*5), stride=2 
3. filter size (3*3) and (5*5), stride=1, zero-padding 
4. Metrics : entropy 


In [17]:
import cv2

In [18]:

import numpy as np


In [19]:
flower = cv2.imread('C:/Users/HP/Desktop/vit/ipynb/Flower.jpg')

In [20]:
#Resizing the image
flower = cv2.resize(flower,(800,600))

In [27]:
# filter size (3*3) and (5*5) stride=1, zero-padding 
filt = np.array([(1,1,1),(1,1,1),(1,1,1)])*(1/9) #filter(3*3)
#filt = np.array([(1,1,1,1,1),(1,1,1,1,1),(1,1,1,1,1),(1,1,1,1,1),(1,1,1,1,1)])*(1/25) #filter (5*5)

In [28]:
S = flower.shape
F = filt.shape

In [29]:
#binary conversion
flowerGray = cv2.cvtColor(flower, cv2.COLOR_BGR2GRAY)
cv2.imshow('original',flowerGray)
cv2.waitKey(0)


-1

In [30]:
#zero padding
R = S[0]+F[0]-1
C = S[1]+F[1]-1
Z = np.zeros((R,C))


In [31]:
for i in range(S[0]):
    for j in range(S[1]):
        Z[i+np.int((F[0]-1)/2),j+np.int((F[1]-1)/2)] = flowerGray[i,j]
print(Z)
        

[[  0.   0.   0. ...   0.   0.   0.]
 [  0. 167. 179. ...  23.  22.   0.]
 [  0. 174. 178. ...  29.  25.   0.]
 ...
 [  0. 129. 112. ...  59.  64.   0.]
 [  0. 151. 127. ...  62.  61.   0.]
 [  0.   0.   0. ...   0.   0.   0.]]


In [32]:
for i in range(S[0]):
    for j in range(S[1]):
        k = Z[i:i+F[0],j:j+F[1]]
        l = np.sum(k*filt)
        flowerGray[i,j]=1
cv2.imshow('final',flowerGray)  
cv2.waitKey(0)
    

-1